/*
 * 站内搜索数据源（search.html 引用）
 * ---------------------------------------------
 * 维护方式与 updates.js 完全一致：每发布一篇新文章，就在对应分组里加一条。
 *   t     必填，文章标题（搜索结果里显示的标题，也参与匹配）
 *   u     必填，跳转链接，如 "courses.html#l2-26"
 *   cat   必填，分类："课程" / "研究" / "专题" / "工具" / "页面"（决定过滤标签归属）
 *   badge 必填，结果左侧小标签："L1"~"L5"（课程）/ "研究" / "专题" / "工具" / "页面"
 *   path  必填，面包屑路径，如 "系统课程 › L2 实操准备"（结果里灰色小字显示）
 *   kw    选填，补充关键词（中英文均可，空格分隔）——用来让搜不到标题原词时也能命中，
 *         例如给 MetaMask 教程加 "小狐狸 钱包"，给入金教程加 "充值 法币 onramp"
 * 顺序不影响搜索（结果会自动按相关度排序），加在所在分组末尾即可。
 */
const SEARCH_INDEX = [
  /* —— L1 · 读懂 Web3 —— */
  { t:"Web1、Web2、Web3：互联网三个时代的本质区别", u:"courses.html#l1-01", cat:"课程", badge:"L1", path:"系统课程 › L1 读懂 Web3", kw:"互联网 时代 演变 web1 web2 web3" },
  { t:"为什么说「数据所有权」是 Web3 最核心的革命", u:"courses.html#l1-02", cat:"课程", badge:"L1", path:"系统课程 › L1 读懂 Web3", kw:"数据 所有权 革命 ownership" },
  { t:"去中心化是什么意思？用一个银行的例子讲清楚", u:"courses.html#l1-03", cat:"课程", badge:"L1", path:"系统课程 › L1 读懂 Web3", kw:"去中心化 银行 decentralization" },
  { t:"丢掉账号密码！Web3 的唯一门票：数字钱包与私钥", u:"courses.html#l1-04", cat:"课程", badge:"L1", path:"系统课程 › L1 读懂 Web3", kw:"钱包 私钥 wallet private key" },
  { t:"区块链是什么？一本谁都能看、谁都不能改的账本", u:"courses.html#l1-05", cat:"课程", badge:"L1", path:"系统课程 › L1 读懂 Web3", kw:"区块链 账本 blockchain ledger" },
  { t:"交易如何被记录和确认？从发出到上链的全过程", u:"courses.html#l1-06", cat:"课程", badge:"L1", path:"系统课程 › L1 读懂 Web3", kw:"交易 确认 上链 transaction" },
  { t:"比特币是什么？为什么它是整个行业的数字黄金", u:"courses.html#l1-07", cat:"课程", badge:"L1", path:"系统课程 › L1 读懂 Web3", kw:"比特币 数字黄金 bitcoin btc" },
  { t:"以太坊是什么？智能合约如何改变了一切", u:"courses.html#l1-08", cat:"课程", badge:"L1", path:"系统课程 › L1 读懂 Web3", kw:"以太坊 智能合约 ethereum eth smart contract" },
  { t:"Solana 是什么？为什么它是目前最活跃的公链生态", u:"courses.html#l1-09", cat:"课程", badge:"L1", path:"系统课程 › L1 读懂 Web3", kw:"solana sol 公链" },
  { t:"以太坊之 L2 是什么", u:"courses.html#l1-10", cat:"课程", badge:"L1", path:"系统课程 › L1 读懂 Web3", kw:"l2 layer2 二层 rollup 扩容" },
  { t:"侧链是什么", u:"courses.html#l1-11", cat:"课程", badge:"L1", path:"系统课程 › L1 读懂 Web3", kw:"侧链 sidechain" },
  { t:"应用链是什么", u:"courses.html#l1-12", cat:"课程", badge:"L1", path:"系统课程 › L1 读懂 Web3", kw:"应用链 appchain" },
  { t:"普通人参与 Web3 的正确姿势", u:"courses.html#l1-13", cat:"课程", badge:"L1", path:"系统课程 › L1 读懂 Web3", kw:"新手 入门 参与" },
  { t:"稳定币是什么？DeFi 的基础货币", u:"courses.html#l1-14", cat:"课程", badge:"L1", path:"系统课程 › L1 读懂 Web3", kw:"稳定币 stablecoin usdt usdc defi" },
  { t:"去中心化交易所（DEX）：没有账号，直接换币", u:"courses.html#l1-15", cat:"课程", badge:"L1", path:"系统课程 › L1 读懂 Web3", kw:"dex 去中心化交易所 换币 swap" },
  { t:"链上借贷协议", u:"courses.html#l1-18", cat:"课程", badge:"L1", path:"系统课程 › L1 读懂 Web3", kw:"借贷 lending aave compound" },
  { t:"流动性挖矿和质押", u:"courses.html#l1-19", cat:"课程", badge:"L1", path:"系统课程 › L1 读懂 Web3", kw:"流动性挖矿 质押 staking yield farming" },
  { t:"预测市场", u:"courses.html#l1-20", cat:"课程", badge:"L1", path:"系统课程 › L1 读懂 Web3", kw:"预测市场 prediction market polymarket" },
  { t:"股票代币化", u:"courses.html#l1-21", cat:"课程", badge:"L1", path:"系统课程 › L1 读懂 Web3", kw:"股票代币化 rwa tokenization xstock" },

  /* —— L2 · Web3 实操准备 —— */
  { t:"CEX vs DEX：如何选择你的第一个交易平台", u:"courses.html#l2-1", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"cex dex 交易所 选择" },
  { t:"币安交易所注册教程（含 KYC 全流程）", u:"courses.html#l2-2", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"币安 binance 注册 kyc 实名" },
  { t:"OKX 注册教程", u:"courses.html#l2-3", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"okx 欧易 注册" },
  { t:"Bybit 注册教程", u:"courses.html#l2-4", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"bybit 注册" },
  { t:"Bitget 注册教程", u:"courses.html#l2-5", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"bitget 注册" },
  { t:"Backpack 注册教程", u:"courses.html#l2-6", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"backpack 注册 solana" },
  { t:"Kraken 注册教程", u:"courses.html#l2-7", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"kraken 注册" },
  { t:"币安 C2C 入金教程（2026 最新）", u:"courses.html#l2-8", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"币安 c2c 入金 充值 法币 buy onramp" },
  { t:"币安法币入金教程", u:"courses.html#l2-9", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"币安 法币 入金 充值" },
  { t:"币安 C2C 出金教程", u:"courses.html#l2-10", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"币安 c2c 出金 提现 withdraw" },
  { t:"币安法币出金教程", u:"courses.html#l2-11", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"币安 法币 出金 提现" },
  { t:"Backpack 出金教程", u:"courses.html#l2-12", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"backpack 出金 提现" },
  { t:"Kraken 出金教程", u:"courses.html#l2-13", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"kraken 出金 提现" },
  { t:"WeChat Pay HK（香港微信支付）开通教程", u:"courses.html#l2-wechat-hk", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"微信支付 香港 wechat pay hk 出入金" },
  { t:"ZA Bank（众安银行）开户教程，2026 最新", u:"courses.html#l2-za-bank", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"za bank 众安银行 香港 开户 港卡 银行卡 出金 入金" },
  { t:"钱包不是存钱的：彻底理解钱包的本质", u:"courses.html#l2-14", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"钱包 本质 wallet" },
  { t:"钱包怎么选：热钱包、冷钱包、硬件钱包对比", u:"courses.html#l2-15", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"热钱包 冷钱包 硬件钱包 ledger hardware wallet" },
  { t:"助记词是什么：BIP-39 标准与 12/24 词的区别", u:"courses.html#l2-16", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"助记词 bip39 seed phrase mnemonic" },
  { t:"助记词怎么保管：防丢防盗的完整方案", u:"courses.html#l2-17", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"助记词 保管 备份 安全 backup" },
  { t:"MetaMask 安装与使用完整教程", u:"courses.html#l2-18", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"metamask 小狐狸 钱包 安装" },
  { t:"如何给钱包添加自定义网络", u:"courses.html#l2-19", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"自定义网络 rpc 添加网络 add network" },
  { t:"如何管理多个钱包账户", u:"courses.html#l2-20", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"多账户 钱包管理 account" },
  { t:"Gas 费是什么：以太坊 EIP-1559 机制详解", u:"courses.html#l2-21", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"gas 手续费 eip1559 矿工费" },
  { t:"如何从交易所提币到钱包", u:"courses.html#l2-22", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"提币 交易所 钱包 withdraw" },
  { t:"如何从钱包发送代币到交易所", u:"courses.html#l2-23", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"发送 代币 充值 deposit" },
  { t:"钱包之间如何转账", u:"courses.html#l2-24", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"转账 transfer 钱包" },
  { t:"如何查看转账记录和确认状态", u:"courses.html#l2-25", cat:"课程", badge:"L2", path:"系统课程 › L2 实操准备", kw:"转账记录 区块浏览器 etherscan 确认" },

  /* —— L3 · Web3 实操进阶 —— */
  { t:"稳定币是什么：DeFi 的基础货币 [全景]", u:"courses.html#l3-1", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"稳定币 stablecoin defi" },
  { t:"锚定机制：稳定币是怎么\"稳定\"的 [机制]", u:"courses.html#l3-2", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"锚定 peg 稳定币机制" },
  { t:"脱锚与储备风险：稳定币真的稳定吗", u:"courses.html#l3-3", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"脱锚 depeg 储备 风险" },
  { t:"中心化稳定币的隐藏权力：黑名单与冻结", u:"courses.html#l3-4", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"黑名单 冻结 中心化 usdt usdc" },
  { t:"稳定币的演进谱系：从 USDT 到收益型稳定币 [演进]", u:"courses.html#l3-5", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"稳定币 演进 收益型 usde" },
  { t:"DEX 是什么：钱包直连的链上交易所 [全景]", u:"courses.html#l3-6", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"dex 去中心化交易所" },
  { t:"AMM 定价机制：x*y=k 的全部秘密 [机制]", u:"courses.html#l3-7", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"amm 定价 xyk uniswap 做市" },
  { t:"滑点、价格影响、MEV：换币的隐藏成本", u:"courses.html#l3-8", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"滑点 slippage mev 价格影响" },
  { t:"做 LP 的代价：无常损失精算", u:"courses.html#l3-9", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"无常损失 impermanent loss lp 流动性" },
  { t:"DEX 的演进谱系：从 Uniswap V2 到聚合器时代 [演进]", u:"courses.html#l3-10", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"dex 演进 uniswap 聚合器" },
  { t:"链上借贷是什么：抵押 ETH 借出稳定币 [全景]", u:"courses.html#l3-11", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"借贷 抵押 lending aave" },
  { t:"超额抵押与健康因子：你什么时候会被清算", u:"courses.html#l3-12", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"超额抵押 健康因子 清算 liquidation" },
  { t:"利率从哪来：利用率曲线与浮动利率 [机制]", u:"courses.html#l3-13", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"利率 利用率 浮动利率 apy" },
  { t:"闪电贷：DeFi 最特别的发明", u:"courses.html#l3-14", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"闪电贷 flash loan" },
  { t:"借贷的演进谱系：从 Compound 到隔离池时代 [演进]", u:"courses.html#l3-15", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"借贷 演进 compound 隔离池 morpho" },
  { t:"收益聚合器是什么：链上的\"智能投顾\" [全景]", u:"courses.html#l3-16", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"收益聚合器 yield aggregator yearn" },
  { t:"收益代币化：本金与收益的分离（PT/YT）[机制]", u:"courses.html#l3-17", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"收益代币化 pt yt pendle" },
  { t:"嵌套风险：聚合器是放大器，不是过滤器", u:"courses.html#l3-18", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"嵌套风险 聚合器 风险" },
  { t:"聚合器的演进谱系：从 Yearn 到 Pendle [演进]", u:"courses.html#l3-19", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"聚合器 演进 yearn pendle" },
  { t:"PoS 质押是什么：以太坊收益的本质 [全景]", u:"courses.html#l3-20", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"pos 质押 staking eth 收益" },
  { t:"流动性凭证机制：stETH 如何代表你的质押", u:"courses.html#l3-21", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"steth 流动性质押 lido lst" },
  { t:"再质押与 AVS：一份质押打几份工的代价", u:"courses.html#l3-22", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"再质押 restaking avs eigenlayer" },
  { t:"质押的演进谱系：从 Lido 到再质押与 LRT [演进]", u:"courses.html#l3-23", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"质押 演进 lido lrt 再质押" },
  { t:"链上永续合约是什么：杠杆交易的基本结构", u:"courses.html#l3-24", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"永续合约 杠杆 perp 合约" },
  { t:"资金费率：永续合约的\"心跳\"机制", u:"courses.html#l3-25", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"资金费率 funding rate 永续" },
  { t:"强平、维持保证金与 ADL：爆仓是怎么发生的", u:"courses.html#l3-26", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"强平 爆仓 保证金 adl liquidation" },
  { t:"链上合约的\"水深\"：滑点、点差、清算费", u:"courses.html#l3-27", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"合约 滑点 点差 清算费" },
  { t:"链上合约的演进谱系：从 dYdX 到 Hyperliquid", u:"courses.html#l3-28", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"合约 演进 dydx hyperliquid" },
  { t:"预测市场是什么：把\"未来\"做成可交易资产 [全景]", u:"courses.html#l3-29", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"预测市场 prediction polymarket" },
  { t:"结算机制与争议：预言机如何裁定输赢", u:"courses.html#l3-30", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"结算 预言机 oracle 争议" },
  { t:"预测市场的演进谱系：从 Augur 到 Polymarket [演进]", u:"courses.html#l3-31", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"预测市场 演进 augur polymarket" },
  { t:"DeFi 全景图：七大业态如何组合运作", u:"courses.html#l3-32", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"defi 全景 业态 组合" },
  { t:"新手参与 DeFi 的资金分配框架", u:"courses.html#l3-33", cat:"课程", badge:"L3", path:"系统课程 › L3 实操进阶", kw:"资金分配 新手 仓位 框架" },

  /* —— L4 · DeFi 协议实战 —— */
  { t:"Uniswap 实操", u:"courses.html#l4-1", cat:"课程", badge:"L4", path:"系统课程 › L4 DeFi 协议实战", kw:"uniswap dex swap 实操" },
  { t:"Jupiter 实操", u:"courses.html#l4-2", cat:"课程", badge:"L4", path:"系统课程 › L4 DeFi 协议实战", kw:"jupiter solana 聚合 dex" },
  { t:"Curve 实操", u:"courses.html#l4-3", cat:"课程", badge:"L4", path:"系统课程 › L4 DeFi 协议实战", kw:"curve 稳定币 dex" },
  { t:"Lido 质押实操", u:"courses.html#l4-4", cat:"课程", badge:"L4", path:"系统课程 › L4 DeFi 协议实战", kw:"lido 质押 steth staking" },
  { t:"EigenLayer 再质押", u:"courses.html#l4-5", cat:"课程", badge:"L4", path:"系统课程 › L4 DeFi 协议实战", kw:"eigenlayer 再质押 restaking avs" },
  { t:"Aave 借贷实操", u:"courses.html#l4-6", cat:"课程", badge:"L4", path:"系统课程 › L4 DeFi 协议实战", kw:"aave 借贷 lending" },
  { t:"Sky（MakerDAO）实操", u:"courses.html#l4-7", cat:"课程", badge:"L4", path:"系统课程 › L4 DeFi 协议实战", kw:"sky makerdao dai 稳定币" },
  { t:"Morpho 实操", u:"courses.html#l4-8", cat:"课程", badge:"L4", path:"系统课程 › L4 DeFi 协议实战", kw:"morpho 借贷 隔离池" },
  { t:"Ethena 实操", u:"courses.html#l4-9", cat:"课程", badge:"L4", path:"系统课程 › L4 DeFi 协议实战", kw:"ethena usde 合成美元" },
  { t:"Pendle 实操", u:"courses.html#l4-10", cat:"课程", badge:"L4", path:"系统课程 › L4 DeFi 协议实战", kw:"pendle pt yt 收益代币化" },
  { t:"Xstock 实操", u:"courses.html#l4-11", cat:"课程", badge:"L4", path:"系统课程 › L4 DeFi 协议实战", kw:"xstock 股票代币化 rwa" },
  { t:"Polymarket 实操", u:"courses.html#l4-12", cat:"课程", badge:"L4", path:"系统课程 › L4 DeFi 协议实战", kw:"polymarket 预测市场" },
  { t:"Hyperliquid 实操", u:"courses.html#l4-13", cat:"课程", badge:"L4", path:"系统课程 › L4 DeFi 协议实战", kw:"hyperliquid 永续合约 perp" },

  /* —— L5 · Web3 项目研究 —— */
  { t:"如何评估一个 Web3 项目：完整研究框架", u:"courses.html#l5-1", cat:"课程", badge:"L5", path:"系统课程 › L5 项目研究", kw:"研究框架 评估 尽调" },
  { t:"白皮书怎么读：提取关键信息的方法", u:"courses.html#l5-2", cat:"课程", badge:"L5", path:"系统课程 › L5 项目研究", kw:"白皮书 whitepaper 阅读" },
  { t:"团队背景调查方法：如何核实创始人信息", u:"courses.html#l5-3", cat:"课程", badge:"L5", path:"系统课程 › L5 项目研究", kw:"团队 背景调查 创始人" },
  { t:"链上数据分析基础：读懂项目的真实使用情况", u:"courses.html#l5-4", cat:"课程", badge:"L5", path:"系统课程 › L5 项目研究", kw:"链上数据 分析 onchain" },
  { t:"TVL 与协议收入解读：区分真实价值与虚假繁荣", u:"courses.html#l5-5", cat:"课程", badge:"L5", path:"系统课程 › L5 项目研究", kw:"tvl 协议收入 估值" },
  { t:"聪明钱追踪：用链上数据发现机构动向", u:"courses.html#l5-6", cat:"课程", badge:"L5", path:"系统课程 › L5 项目研究", kw:"聪明钱 smart money nansen 追踪" },
  { t:"Dune Analytics 实战：读懂并复用链上数据看板", u:"courses.html#l5-7", cat:"课程", badge:"L5", path:"系统课程 › L5 项目研究", kw:"dune analytics 数据看板 sql" },
  { t:"代币经济模型分析：判断一个代币是否值得持有", u:"courses.html#l5-8", cat:"课程", badge:"L5", path:"系统课程 › L5 项目研究", kw:"代币经济 tokenomics 模型" },
  { t:"解锁计划与抛压评估：别在大户出货时接盘", u:"courses.html#l5-9", cat:"课程", badge:"L5", path:"系统课程 › L5 项目研究", kw:"解锁 抛压 vesting unlock" },
  { t:"如何辨别早期项目机会：Testnet 与空投研究方法", u:"courses.html#l5-10", cat:"课程", badge:"L5", path:"系统课程 › L5 项目研究", kw:"空投 airdrop testnet 早期 撸毛" },

  /* —— 项目研究（深度研报） —— */
  { t:"Web3 项目基本面研究框架", u:"research.html#r-framework", cat:"研究", badge:"研究", path:"项目研究 › 研究方法论", kw:"基本面 研究框架 方法论" },
  { t:"代币经济学深度解析", u:"research.html#r-tokenomics", cat:"研究", badge:"研究", path:"项目研究 › 研究方法论", kw:"代币经济学 tokenomics 供应 解锁" },
  { t:"Web3 估值方法论：FDV / TVL / P/S / P/F", u:"research.html#r-valuation", cat:"研究", badge:"研究", path:"项目研究 › 研究方法论", kw:"估值 fdv tvl ps pf 市销率" },
  { t:"竞争格局分析：DEX / 借贷 / LSD 赛道", u:"research.html#r-competition", cat:"研究", badge:"研究", path:"项目研究 › 研究方法论", kw:"竞争格局 赛道 dex 借贷 lsd" },
  { t:"Hyperliquid 深度研究", u:"research.html#r-hyperliquid", cat:"研究", badge:"研究", path:"项目研究 › 协议案例", kw:"hyperliquid 永续 perp dex" },
  { t:"Aave 深度研究", u:"research.html#r-aave", cat:"研究", badge:"研究", path:"项目研究 › 协议案例", kw:"aave 借贷 lending" },
  { t:"Jupiter 深度研究", u:"research.html#r-jupiter", cat:"研究", badge:"研究", path:"项目研究 › 协议案例", kw:"jupiter solana 聚合器" },
  { t:"Uniswap 深度研究", u:"research.html#r-uniswap", cat:"研究", badge:"研究", path:"项目研究 › 协议案例", kw:"uniswap dex amm" },
  { t:"Circle / USDC 深度研究", u:"research.html#r-circle", cat:"研究", badge:"研究", path:"项目研究 › 协议案例", kw:"circle usdc 稳定币" },
  { t:"Chainlink 深度研究", u:"research.html#r-chainlink", cat:"研究", badge:"研究", path:"项目研究 › 协议案例", kw:"chainlink link 预言机 oracle" },
  { t:"Ethereum 深度研究", u:"research.html#r-ethereum", cat:"研究", badge:"研究", path:"项目研究 › 协议案例", kw:"ethereum eth 以太坊" },
  { t:"BNB Chain 深度研究", u:"research.html#r-bnb", cat:"研究", badge:"研究", path:"项目研究 › 协议案例", kw:"bnb chain 币安链 bsc" },
  { t:"Pump.fun 深度研究", u:"research.html#r-pumpfun", cat:"研究", badge:"研究", path:"项目研究 › 协议案例", kw:"pumpfun 发币 meme solana" },
  { t:"Pendle 深度研究", u:"research.html#r-pendle", cat:"研究", badge:"研究", path:"项目研究 › 协议案例", kw:"pendle 收益代币化 pt yt" },
  { t:"Ethena 深度研究", u:"research.html#r-ethena", cat:"研究", badge:"研究", path:"项目研究 › 协议案例", kw:"ethena usde 合成美元 收益型稳定币" },

  /* —— 专题与页面 —— */
  { t:"出入金涉及政策风险与防控", u:"topics.html#series-io", cat:"专题", badge:"专题", path:"专题系列", kw:"出入金 政策 风险 防控 反诈 银行卡" },
  { t:"专题系列总览", u:"topics.html", cat:"专题", badge:"专题", path:"专题系列", kw:"专题 系列 深度" },
  { t:"国内加密政策一览表", u:"policy.html", cat:"专题", badge:"专题", path:"专题系列 › 政策", kw:"政策 加密 国内 监管 合规 法律" },
  { t:"常用工具导航", u:"tools.html", cat:"工具", badge:"工具", path:"Web3 工具", kw:"工具 导航 钱包 数据 安全 metamask dune defillama" },
  { t:"关于 DF的加密笔记", u:"about.html", cat:"页面", badge:"页面", path:"站点", kw:"关于 about 介绍" },
  { t:"加入社群", u:"community.html", cat:"页面", badge:"页面", path:"站点", kw:"社群 community 加入 群" }
];
